title: Gazali Agboola
logo: assets/img/gazal-headshot.jpg
description: Ph.D. candidate in Data Science & Analytics, skilled in machine learning and time series forecasting. Seeking an opportunity in a data science role.
show_downloads: true
theme: jekyll-theme-minimal
